require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  Exclude:
    - 'bin/bundle'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/helpers/application_helper.rb'
    - 'config/application.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'

Layout/LineLength:
  Max: 198

Metrics/PerceivedComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 12

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/BlockLength:
  Max: 47

